=== xsyetopz/go-mamusiabtw/schemas/signature.schema.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/main/schemas/signature.schema.v1.json",
  "title": "mamusiabtw plugin signature",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "key_id": {
      "type": "string",
      "minLength": 1
    },
    "hash_b64": {
      "type": "string",
      "minLength": 1
    },
    "signature_b64": {
      "type": "string",
      "minLength": 1
    },
    "algorithm": {
      "type": "string",
      "enum": [
        "ed25519-sha256"
      ]
    }
  },
  "required": [
    "key_id",
    "signature_b64"
  ]
}

=== xsyetopz/go-mamusiabtw/plugins/wellness/signature.json
{
  "$schema": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/refs/heads/main/schemas/signature.schema.v1.json",
  "algorithm": "ed25519-sha256",
  "hash_b64": "e7JsIk5YwCageEjf0CioANxRiNuiPkF2bOq8y6kmYVc=",
  "key_id": "official-release-2026-04",
  "signature_b64": "ZLPX+qMVY4/BkCA8zqdzM+SSz17g+cKsOMihpUV6U7VAkBYVvA6NSjzR4OKDvDAgHIAom0WZp3gZxD2aTnYxAQ=="
}

=== xsyetopz/go-mamusiabtw/plugins/moderation/signature.json
{
  "$schema": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/refs/heads/main/schemas/signature.schema.v1.json",
  "algorithm": "ed25519-sha256",
  "hash_b64": "WwIlkQC/lkP2hK2wtG/P/sPoHC1/Ag+/nMzwD3k2V/8=",
  "key_id": "official-release-2026-04",
  "signature_b64": "3kZ4jXp75XhjO8CHHYTFLsF5+aLdWdG6sVEuEaCbZd3QmQrDwogyRciB0sghJBjy3VH/5WEbiqt47NCbn+rpCw=="
}

=== xsyetopz/go-mamusiabtw/plugins/info/signature.json
{
  "$schema": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/refs/heads/main/schemas/signature.schema.v1.json",
  "algorithm": "ed25519-sha256",
  "hash_b64": "RNroXYl30cIlb5kVx7RmZgmNNz7pvH36pRD9tnR0+ws=",
  "key_id": "official-release-2026-04",
  "signature_b64": "+/+FDEvwY6F1Z5T8+u1D06TD9QbO97PoBSxXE6OgsL+NMuSuhbssHwvP+sMGHmpuUFXE5Zwh3xYzTX/S4KfuAQ=="
}

=== xsyetopz/go-mamusiabtw/plugins/manager/signature.json
{
  "$schema": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/refs/heads/main/schemas/signature.schema.v1.json",
  "algorithm": "ed25519-sha256",
  "hash_b64": "MtZgG6jX8EwkD6tbf6hAFyk5EiW/Mh1QyQj0KcLY+Gw=",
  "key_id": "official-release-2026-04",
  "signature_b64": "dA4eWJohG+rApGDQfFQiRDAmWWKRSBcBYC2inaOkpHFa9XThgYbfdHh0/i+u8FSs+5HiuwRuWiPbdv5cVdDXDg=="
}

=== xsyetopz/go-mamusiabtw/plugins/fun/signature.json
{
  "$schema": "https://raw.githubusercontent.com/xsyetopz/go-mamusiabtw/refs/heads/main/schemas/signature.schema.v1.json",
  "algorithm": "ed25519-sha256",
  "hash_b64": "InXfPk6STgFGBCBIrLLGOve1syGndk+00bj7/Ju/Y9Q=",
  "key_id": "official-release-2026-04",
  "signature_b64": "o333bMMc7egNDF0ISroGdu24CI2FNrEUKGwP5yt6jR3aLOJYvp/j8RimT4NRgb9hACcahqDqzecAUK9f9kE/Cg=="
}
